<?php

/**
 * @file
 * Add client IP addresses to outgoing email for tracking the source of spam.
 */

/**
 * Implements hook_menu().
 */
function x_originating_ip_menu() {
  $items = array();

  $items['admin/config/system/x_originating_ip'] = array(
    'title' => 'X-Originating-IP',
    'description' => 'Use alternative headers for outgoing email identifying the originating IP address of the remote client.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('x_originating_ip_settings'),
    'file' => 'x_originating_ip.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_mail_alter().
 */
function x_originating_ip_mail_alter(&$message) {
  $header = variable_get('x_originating_ip_header', 'X-Originating-IP');
  $message['headers'][$header] = '[' . ip_address() . ']';
}

function _x_originating_ip_headers() {
  return array(
    'X-Originating-IP' => 'X-Originating-IP',
    'X-Sender' => 'X-Sender',
    'X-SenderIP' => 'X-SenderIP',
    'X-Sender-IP' => 'X-Sender-IP',
    'X-Apparently-From' => 'X-Apparently-From',
  );
}
