<?php

/**
 * @file
 * Add client IP addresses to outgoing email for tracking the source of spam.
 */

/**
 * Implements hook_mail_alter().
 */
function x_originating_ip_mail_alter(&$message) {
  $ip_address = ip_address();

  // the normal headers should be sufficient if it's originating from the
  // server anyway, so don't include a header for localhost 127.0.0.1
  if ($ip_address != '127.0.0.1') {
    $message['headers']['X-Originating-IP'] = '[' . $ip_address . ']';
  }
}
